# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='doctores',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='doctor',
        ),
    ]
